[Jordi]Lecture/santi jordi routes
SkylabCoders/skylab-bootcamp-202007 pull request #931
Opened 2020-08-19 18:33 UTC by Jordimm11

2020-08-19 21:03 UTC, daniamcode commented
ui, estàs modificant fitxers d'en Francesc...

2020-08-20 06:35 UTC, fcesc-code requested changes
Jordi you have added some files of mine in this pull request, please remove them

2020-08-20 07:02 UTC, fcesc-code approved these changes

2020-08-20 07:03 UTC, gerardramonp approved these changes
En francesc m'ha dit que faci aprove, si ell ho diu, jo que he de fer.....

2020-08-20 07:05 UTC, alexeh approved these changes

2020-08-20 07:21 UTC, gemmas95 requested changes
Jordi be careful, you're changing Gabri files!

2020-08-20 07:32 UTC, Jordimm11 commented
> Jordi be careful, you're changing Gabri files!

Ja ho hem mirat amb ell...està resolt. Avisa'm quan aprovis! gràcies!

2020-08-20 07:37 UTC, gemmas95 approved these changes

2020-08-20 07:38 UTC, merged